export const TEXTS = {
    settingsLayout: "Стиль статблока",
    settingsLayoutDescription: "Внешний вид и разметка статблока",
    settingsLayout5e: "D&D 5 редакции",
    settingsLayoutTtg: "TTG Club",
    fullSpell: "Заклинание",
    noticeClipboardSuccess: " - успешно скопировано.",
    ribbonActionBestiaryTitle: "Бестиарий",
    ribbonActionSpellbookTitle: "Книга заклинаний",
    ribbonActionInitiativeTrackerTitle: "Трекер инициативы",
    sidePanelBestiaryTitle: "Бестиарий",
    sidePanelSpellbookTitle: "Книга заклинаний",
    sidePanelInitiativeTrackerTitle: "Трекер инициативы",
    bestiarySearchPlaceholder: "Поиск по имени в бестиарии",
    spellbookSearchPlaceholder: "Поиск по книге заклинаний",
    sidePanelBestiarySearchClear: "Убрать статблок",
    addStatblockModalTwoColumns: "2 столбца",
    addStatblockModalSubmit: "Добавить",
    addSpellModalSubmit: "Добавить",
    layoutSource: "Источник",
    layoutArmorClass: "Класс доспеха",
    layoutHits: "Хиты",
    layoutSpeed: "Скорость",
    layoutFt: "фт",
    layoutStr: "СИЛ",
    layoutDex: "ЛОВ",
    layoutCon: "ТЕЛ",
    layoutInt: "ИНТ",
    layoutWis: "МУД",
    layoutCha: "ХАР",
    layoutSave: "Спасбросок",
    layoutSaves: "Спасброски",
    layoutSkill: "Навык",
    layoutSkills: "Навыки",
    layoutDamageVulnerabilities: "Уязвимость к урону",
    layoutDamageResistances: "Сопротивление к урону",
    layoutDamageImmunities: "Иммунитет к урону",
    layoutConditionImmunities: "Иммунитет к состоянию",
    layoutPassivePerception: "пассивная внимательность",
    layoutSenses: "Чувства",
    layoutLanguages: "Языки",
    layoutChallengeRating: "Опасность",
    layoutActions: "Действия",
    layoutBonusActions: "Бонусные действия",
    layoutReactions: "Реакции",
    layoutLegendaryActions: "Легендарные действия",
    layoutLair: "Логово",
    layoutLairActions: "Действия логова",
    layoutRegionalEffects: "Региональные эффекты",
    layoutDescription: "Описание",
    commandAddStatblock: "Добавить статблок",
    commandAddWideStatblock: "Добавить широкий статблок",
    commandAddSpell: "Добавить заклинание",
    commandAddEncounter: "Добавить боевое столкновение",
    initiativeTrackerHintCopy: "Копировать",
    initiativeTrackerHintPaste: "Вставить",
    initiativeTrackerHintNext: "Следующий ход",
    initiativeTrackerHintStop: "Остановить",
    initiativeTrackerHintRoll: "Бросить инициативу",
    initiativeTrackerHintSort: "Сортировать по инициативе",
    initiativeTrackerHintInitiative: "Инициатива",
    initiativeTrackerHintClear: "Убрать",
    initiativeTrackerHintAdd: "Добавить",
    initiativeTrackerHintHits: "Хиты",
    initiativeTrackerHintHitsCurrent: "Текущие",
    initiativeTrackerHintHitsTemporary: "Временные",
    initiativeTrackerHintHitsMax: "Максимум",
    initiativeTrackerHintArmorClass: "Класс Доспеха",
    spellCastingTime: "Время",
    spellRange: "Дистанция",
    spellComponents: "Компоненты",
    spellDuration: "Длительность",
    spellLevel: "круг",
    spellCantrip: "заговор",
    spellVerbal: "В",
    spellSomatic: "С",
    spellMaterial: "М",
    spellRitual: "Ритуал",
    spellClasses: "Классы",
    spellSubclasses: "Подклассы",
};
