export const TEXTS = {
    settingsLayout: "Стиль статблока",
    settingsLayoutDescription: "Внешний вид и разметка статблока",
    settingsLayout5e: "D&D 5 редакции",
    settingsLayoutTtg: "TTG Club",
    noticeClipboardSuccess: " - успешно скопировано.",
    ribbonActionTitle: "Открыть бестиарий",
    sidePanelBestiaryTitle: "Бестиарий",
    bestiarySearchPlaceholder: "Поиск по имени в бестиарии",
    sidePanelBestiarySearchClear: "Убрать статблок",
    addStatblockModalTwoColumns: "2 столбца",
    addStatblockModalSubmit: "Добавить",
    layoutSource: "Источник",
    layoutArmorClass: "Класс доспеха",
    layoutHits: "Хиты",
    layoutSpeed: "Скорость",
    layoutFt: "фт",
    layoutStr: "СИЛ",
    layoutDex: "ЛОВ",
    layoutCon: "ТЕЛ",
    layoutInt: "ИНТ",
    layoutWis: "МУД",
    layoutCha: "ХАР",
    layoutSaves: "Спасброски",
    layoutSkills: "Навыки",
    layoutDamageVulnerabilities: "Уязвимость к урону",
    layoutDamageResistances: "Сопротивление к урону",
    layoutDamageImmunities: "Иммунитет к урону",
    layoutConditionImmunities: "Иммунитет к состоянию",
    layoutPassivePerception: "пассивная внимательность",
    layoutSenses: "Чувства",
    layoutLanguages: "Языки",
    layoutChallengeRating: "Опасность",
    layoutActions: "Действия",
    layoutBonusActions: "Бонусные действия",
    layoutReactions: "Реакции",
    layoutLegendaryActions: "Легендарные действия",
    layoutLair: "Логово",
    layoutLairActions: "Действия логова",
    layoutRegionalEffects: "Региональные эффекты",
    commandAddStatblock: "Добавить статблок",
    commandAddWideStatblock: "Добавить широкий статблок",
}
