import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import esbuildSvelte from 'esbuild-svelte';
import { sveltePreprocess } from 'svelte-preprocess';
import { readFile, writeFile, rm } from 'node:fs/promises';

const embeddedCssMarker = "/* DND_DM_TOOLS_BUNDLED_CSS */";

const embedObsidianCss = {
	name: "embed-obsidian-css",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;

			let bundledCss;
			try {
				bundledCss = await readFile("main.css", "utf8");
			} catch {
				return;
			}

			const currentStyles = await readFile("styles.css", "utf8");
			const markerIndex = currentStyles.indexOf(embeddedCssMarker);
			const baseStyles = markerIndex >= 0 ? currentStyles.slice(0, markerIndex).trimEnd() : currentStyles.trimEnd();
			await writeFile("styles.css", `${baseStyles}\n\n${embeddedCssMarker}\n${bundledCss.trim()}\n`);
			await rm("main.css", { force: true });
		});
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	alias: {
		ws: "./node_modules/ws/index.js",
	},
	loader: {
		'.svg': 'text',
		'.wasm': 'binary',
		'.woff': 'dataurl',
		'.woff2': 'dataurl',
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
		...builtins.map((module) => `node:${module}`)],
	format: "cjs",
	target: "es2018",
	define: {
		__DND_DM_TOOLS_DEV__: JSON.stringify(!prod),
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: 'injected' },
			preprocess: sveltePreprocess(),
		}),
		embedObsidianCss,
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
